# Generated by Django 4.0.5 on 2022-07-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='img',
            field=models.ImageField(default=True, upload_to=''),
        ),
    ]
